Vagrant.configure("2") do |config|
 config.vm.box = "centos/7"
 config.vm.box_version = "1804.02"

 $VAR = <<SCRIPT
  pwd
SCRIPT
	
 $script = <<SCRIPT
 cp /root/timer/watchlog /etc/sysconfig/
 cp /root/timer/watchlog.log /var/log/
 cp /root/timer/watchlog.sh /opt/
 cp /root/timer/watchlog.service /etc/systemd/system/
 cp /root/timer/watchlog.timer /etc/systemd/system/
 systemctl daemon-reload
 systemctl start watchlog.timer 
SCRIPT

 config.vm.synced_folder "#{ENV['VAR']}", "/root" 

 config.vm.box_check_update = false
 config.vm.provision "shell", inline: $script

end
