# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:R1 => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "vlan-12"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "vlan-13"},
                  {ip: '10.1.0.1', adapter: 4, netmask: "255.255.0.0"},
                   
                ]
  },
:R2 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: "vlan-12"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: "vlan-23"},
                   {ip: '10.2.0.1', adapter: 4, netmask: "255.255.0.0"},
                  ]
  },
:R3 => {
       :box_name => "centos/7",
       :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "vlan-13"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "vlan-23"},
                  {ip: '10.3.0.1', adapter: 4, netmask: "255.255.0.0"},
                ]
},

	
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        config.vm.provision "ansible" do |ansible|
          ansible.verbose = "vvv"
          ansible.playbook = "provisioning/playbook.yml"
          ansible.become = "true"
          end
      end  
  end
end