# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :otuslinuxdz2 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.102',
	:disks => {
		:sata1 => {
			:dfile => home + '/dz2_raid/sata7.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
                       :dfile => home + '/dz2_raid/sata8.vdi',
                       :size => 250, # Megabytes
	      		:port => 2
		},
               :sata3 => {
                       :dfile => home + '/dz2_raid/sata9.vdi',
                       :size => 250,
                       :port => 3
                },
                :sata4 => {
                        :dfile => home + '/dz2_raid/sata10.vdi',
                        :size => 250, # Megabytes
                        :port => 4
                },
		:sata5 => {
			:dfile => home + '/dz2_raid/sata11.vdi',
			:size => 250,
			:port => 5
		}

	}

		
  },
}

Vagrant.configure("2") do |config|
	
	
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
	      yum install -y e2fsprogs.x86_64 nano vim
#	      sudo mdadm --create /dev/md5 --level=5 --raid-devices=3 /dev/sd[b-d]
#	      sudo mkfs.ext4 /dev/md5
#	      sudo mkdir /raid5
#	      sudo mount /dev/md5 /raid5
#	      sudo echo /dev/md5 /raid5 ext4 defaults 0 0 >> /etc/fstab
#	      sudo mdadm --detail --scan --verbose >> /etc/mdadm.conf
	
  	  SHELL

      end
  end
end

